version: '{build}'

clone_depth: 50

environment:
  JRE8_HOME: $(ProgramFiles)\Java\jdk1.8.0\jre
  ANT_VERSION: 1.10.5

  matrix:
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk11
      VT_API_KEY:
        secure: 3sqJDjLAS708tR/LiAqKLZTnLLrhGJuWVzzI4nCjLbUUsZB+PPRG3y0BWWnMo14CDhBT4v6yjHTA23RdopoHDWJlBcGhKELKZOLhHsnJLU8=

install:
  - cinst ant -i --version %ANT_VERSION%
  - PATH %ANT_HOME%\bin;%PATH%

before_build:
  - ant -diagnostics

build_script:
  - ant all

after_build:
  - IF "%APPVEYOR_REPO_TAG%" == "true" IF DEFINED VT_API_KEY SET ARTIFACTS_PATH=build\*.* & FOR /R build %%f IN (*.exe *.tar.gz) DO IF NOT %%~xf == .exec ECHO Submitting file "%%f" to VirusTotal... & curl -v -F "file=@%%f" -F apikey=%VT_API_KEY% https://www.virustotal.com/vtapi/v2/file/scan & ECHO File "%%f" submitted to VirusTotal. & TIMEOUT 15 /NOBREAK

artifacts:
  - path: $(ARTIFACTS_PATH)
    type: file

deploy:
  description: 'Autogenerated'
  provider: GitHub
  auth_token:
    secure: iZF8b6d29Wk2VAubvw8tEwOMt0kB0Krq2e0Ie0Up15EfEfEBnvgs05/LbjhIODWi
  draft: true
  on:
    appveyor_repo_tag: true
